# Generated by Django 5.1.3 on 2025-04-29 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_contract_completed_date_contract_is_terms_accepted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksubmission',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='worksubmission',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='work_submissions/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='worksubmission',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_submissions', to='contract.contract'),
        ),
        migrations.AlterField(
            model_name='worksubmission',
            name='description',
            field=models.TextField(blank=True, help_text='Description of changes or deliverables.'),
        ),
    ]
