# Generated by Django 5.1.3 on 2025-04-29 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_remove_worksubmission_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='terms',
        ),
    ]
