# Generated by Django 5.1.3 on 2025-04-29 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_remove_contract_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='is_terms_accepted',
        ),
    ]
