# Generated by Django 5.1.3 on 2025-04-29 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_remove_contract_is_terms_accepted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkSubmission',
        ),
    ]
