# Generated by Django 5.1.3 on 2025-05-31 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_task_tasksubmission_workspace_task_workspace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasksubmission',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='tasksubmission',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='final_attachment',
            field=models.FileField(blank=True, null=True, upload_to='final_submissions/'),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='final_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('final_submitted', 'Final Work Submitted'), ('completed', 'Completed')], default='submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='attachment',
            field=models.FileField(default=1, upload_to='submissions/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='tasksubmission',
            table=None,
        ),
    ]
