# Generated by Django 5.1.3 on 2025-05-31 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_alter_tasksubmission_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksubmission',
            name='task',
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contract.workspace'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='task_attachments/'),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
