# Generated by Django 5.1.3 on 2025-05-31 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0009_remove_tasksubmission_task_tasksubmission_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksubmission',
            name='title',
        ),
    ]
