# Generated by Django 5.1.3 on 2025-05-31 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0010_remove_tasksubmission_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewer_type',
            field=models.CharField(choices=[('client', 'Client'), ('freelancer', 'Freelancer')], default=1, help_text='Whether the review is from client or freelancer', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='contract.contract'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('contract', 'reviewer_type')},
        ),
    ]
