# Generated by Django 5.1.3 on 2025-05-31 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0011_review_reviewer_type_alter_review_contract_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_uuid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='contract.contract'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='transaction',
            table=None,
        ),
    ]
