# Generated by Django 5.1.3 on 2025-04-12 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_alter_otpcode_options_alter_user_options_and_more'),
        ('projects', '0003_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO language code', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Full language name', max_length=100)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_of_experience', models.PositiveIntegerField(default=0, help_text='Total years of professional experience')),
                ('professional_title', models.CharField(blank=True, help_text='Professional title/headline (e.g., Full-Stack Developer)', max_length=100)),
                ('expertise_level', models.CharField(blank=True, choices=[('entry', 'Entry Level'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], help_text='Skill level in their field', max_length=20)),
                ('availability', models.CharField(blank=True, choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('not-available', 'Not Available')], help_text='Current work availability status', max_length=20)),
                ('preferred_project_duration', models.CharField(blank=True, choices=[('short', 'Less than 1 month'), ('medium', '1-3 months'), ('long', '3+ months')], help_text='Preferred engagement duration', max_length=20)),
                ('communication_preference', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('chat', 'Chat')], help_text='Preferred communication method', max_length=20)),
                ('portfolio_link', models.URLField(blank=True, help_text='Link to portfolio website')),
                ('github_link', models.URLField(blank=True, help_text='Link to GitHub profile')),
                ('linkedin_link', models.URLField(blank=True, help_text='Link to LinkedIn profile')),
                ('skills', models.ManyToManyField(blank=True, help_text='Skills possessed by the freelancer', related_name='freelancers', to='projects.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Freelancer Profile',
                'verbose_name_plural': 'Freelancer Profiles',
                'db_table': 'freelancer',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currently_studying', models.BooleanField(default=False)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, help_text='Grade Point Average (0.00-4.00 scale)', max_digits=4, null=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='freelancerprofile.freelancer')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education Records',
                'db_table': 'education',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('employment_type', models.CharField(blank=True, choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currently_working', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.country')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='freelancerprofile.freelancer')),
                ('skills', models.ManyToManyField(blank=True, related_name='work_experiences', to='projects.skill')),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experiences',
                'db_table': 'work_experience',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FreelancerLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.IntegerField(choices=[(1, 'Basic'), (2, 'Conversational'), (3, 'Fluent'), (4, 'Advanced'), (5, 'Native/Bilingual')], help_text='Language proficiency level')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='freelancerprofile.freelancer')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancers', to='freelancerprofile.language')),
            ],
            options={
                'verbose_name': 'Freelancer Language',
                'verbose_name_plural': 'Freelancer Languages',
                'db_table': 'freelancer_language',
                'unique_together': {('freelancer', 'language')},
            },
        ),
    ]
