# Generated by Django 5.1.3 on 2025-02-24 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_alter_freelancer_experience_years'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('education_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('education_level', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('freelancer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='accounts.freelancer')),
            ],
            options={
                'db_table': 'education',
            },
        ),
    ]
