# Generated by Django 5.1.3 on 2025-04-25 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancerprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancerservice',
            name='category',
        ),
        migrations.RemoveField(
            model_name='freelancerservice',
            name='freelancer',
        ),
        migrations.RemoveField(
            model_name='freelancerservice',
            name='icon_class',
        ),
    ]
