# Generated by Django 5.1.3 on 2025-02-24 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancerprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='freelancer_id',
            new_name='freelancer',
        ),
    ]
