# Generated by Django 5.1.3 on 2025-04-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancerprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('high_school', 'High School Diploma'), ('associate', 'Associate Degree'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'Doctorate (PhD)'), ('diploma', 'Diploma'), ('certificate', 'Certificate'), ('mba', 'MBA'), ('other', 'Other')], default='bachelor', max_length=20),
        ),
    ]
