# Generated by Django 5.1.3 on 2025-04-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancerprofile', '0002_remove_freelancerservice_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FreelancerService',
        ),
    ]
