# Generated by Django 5.1.3 on 2025-04-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancerprofile', '0002_alter_education_degree'),
        ('projects', '0005_alter_projectattachment_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelanceServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_class', models.CharField(blank=True, max_length=100, null=True)),
                ('skills', models.ManyToManyField(related_name='service_categories', to='projects.skill')),
            ],
            options={
                'db_table': 'freelance_service_category',
            },
        ),
    ]
