# Generated by Django 5.1.3 on 2025-02-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancerprofile', '0002_rename_freelancer_id_education_freelancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_images/'),
        ),
    ]
