# Generated by Django 5.1.3 on 2025-04-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancerprofile', '0003_freelanceservicecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Manually mark a freelancer as featured'),
        ),
    ]
