# Generated by Django 5.1.3 on 2025-02-24 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_freelancer_experience_years'),
        ('freelancerprofile', '0003_education_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('certificate_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('certificate_name', models.CharField(max_length=255)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('certificate_logo', models.ImageField(blank=True, null=True, upload_to='certificate_images/')),
                ('certificate_url', models.URLField(blank=True, max_length=500, null=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='accounts.freelancer')),
            ],
            options={
                'db_table': 'certificate',
            },
        ),
    ]
