# Generated by Django 5.1.3 on 2025-02-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancerprofile', '0004_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='issuing_organization',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
