# Generated by Django 5.1.3 on 2025-04-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancerprofile', '0004_freelancer_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='badge',
            field=models.CharField(blank=True, choices=[('top_rated', 'Top Rated'), ('pro_verified', 'Pro Verified'), ('rising_talent', 'Rising Talent')], help_text='Badge earned by the freelancer', max_length=20),
        ),
    ]
