# Generated by Django 5.1.3 on 2025-02-24 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancerprofile', '0005_certificate_issuing_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='issuing_organization',
            new_name='certificate_provider',
        ),
    ]
