# Generated by Django 5.1.3 on 2024-11-30 16:28

import accounts.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTPCode",
            fields=[
                ("otp_id", models.AutoField(primary_key=True, serialize=False)),
                ("otp_code", models.CharField(max_length=6)),
                ("email", models.EmailField(max_length=254)),
                (
                    "otp_generated_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "otp_expired_time",
                    models.DateTimeField(default=accounts.models.default_expired_time),
                ),
            ],
        ),
    ]
