# Generated by Django 5.1.3 on 2024-12-13 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
        migrations.AlterModelTable(
            name='freelancer',
            table='freelancer',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
