# Generated by Django 5.1.3 on 2025-04-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_city_country_user_city_city_country_user_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='phone_code',
        ),
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
