# Generated by Django 5.1.3 on 2024-11-30 16:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_otpcode"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="otpcode",
            table="otp_code",
        ),
    ]
