# Generated by Django 5.1.3 on 2025-04-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_country_phone_code_alter_city_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_google_auth',
            field=models.BooleanField(default=False),
        ),
    ]
