# Generated by Django 5.1.3 on 2024-12-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_remove_user_is_active_remove_user_is_staff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="credential_hash",
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
