# Generated by Django 5.1.3 on 2024-12-01 08:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_user_credential_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="credential_hash",
        ),
    ]
