# Generated by Django 5.1.3 on 2025-02-23 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_groups_remove_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='skills',
        ),
    ]
