# Generated by Django 5.1.3 on 2025-02-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_freelancer_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, help_text='Years of experience', null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='languages',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
