# Generated by Django 5.1.3 on 2025-04-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_method',
            field=models.CharField(choices=[('traditional', 'Traditional'), ('google', 'Google')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
