# Generated by Django 5.1.3 on 2025-02-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_freelancer_bio_freelancer_city_freelancer_country_and_more'),
        ('projects', '0005_remove_skill_category_delete_skillcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='skills',
            field=models.ManyToManyField(to='projects.skill'),
        ),
    ]
