# Generated by Django 5.1.3 on 2025-04-06 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_registration_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='registration_method',
            new_name='auth_method',
        ),
    ]
