# Generated by Django 5.1.3 on 2025-02-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_freelancer_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='experience_years',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
