# Generated by Django 5.1.3 on 2025-04-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_otpcode_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_method',
            field=models.CharField(choices=[('traditional', 'Traditional'), ('google', 'Google'), ('github', 'GitHub')], max_length=20),
        ),
    ]
