# Generated by Django 5.1.3 on 2025-02-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_freelancer_experience_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='experience_years',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
