# Generated by Django 5.1.3 on 2025-04-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_auth_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_method',
            field=models.CharField(choices=[('traditional', 'Traditional'), ('google', 'Google')], max_length=20),
        ),
    ]
