# Generated by Django 5.1.3 on 2025-01-03 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_country_city'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='city',
        ),
        migrations.AlterModelTable(
            name='country',
            table='country',
        ),
    ]
