# Generated by Django 5.1.3 on 2025-01-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_city_table_alter_country_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='postal_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
