# Generated by Django 5.1.3 on 2025-01-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_delete_city_delete_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='postal_code',
        ),
    ]
