# Generated by Django 5.1.3 on 2025-04-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Any extra information or project guidelines'),
        ),
        migrations.AddField(
            model_name='project',
            name='key_requirements',
            field=models.TextField(blank=True, help_text='List of key requirements, one per line'),
        ),
    ]
