# Generated by Django 5.1.3 on 2025-04-08 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientprofile', '0001_initial'),
        ('projects', '0002_projectcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_fixed_price', models.BooleanField(default=True, verbose_name='Fixed Price Project')),
                ('fixed_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Published'), ('in progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('estimated_duration', models.IntegerField(help_text='Duration in weeks')),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='entry', max_length=15)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='project_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.projectcategory')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='clientprofile.client')),
                ('skills_required', models.ManyToManyField(related_name='projects', to='projects.skill')),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
