# Generated by Django 5.1.3 on 2025-04-25 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_additional_info_project_key_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_skills', to='projects.project')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_skills', to='projects.skill')),
            ],
            options={
                'db_table': 'project_skill',
                'unique_together': {('project', 'skill')},
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='skills_required',
            field=models.ManyToManyField(related_name='projects', through='projects.ProjectSkill', to='projects.skill'),
        ),
    ]
