# Generated by Django 5.1.3 on 2025-02-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='projectcategory',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
