# Generated by Django 5.1.3 on 2024-12-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='duration',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, help_text='Category of the project', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(help_text='Deadline of the project (in YYYY-MM-DD format)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Project image', null=True, upload_to='project_images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.CharField(blank=True, help_text='Skills required for the project', max_length=255, null=True),
        ),
    ]
