# Generated by Django 5.1.3 on 2025-02-13 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_projectcategory_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='skillcategory',
            name='description',
        ),
    ]
