# Generated by Django 5.1.3 on 2024-12-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_duration_project_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
