# Generated by Django 5.1.3 on 2025-04-12 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_attachment_alter_project_status_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projectattachment',
            table='project_attachment',
        ),
    ]
