# Generated by Django 5.1.3 on 2025-02-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_projectcategory_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.DeleteModel(
            name='SkillCategory',
        ),
    ]
