# Generated by Django 5.1.3 on 2024-12-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_skills_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
