# Generated by Django 5.1.3 on 2024-12-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_skillcategory_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillcategory',
            name='description',
            field=models.TextField(blank=True, help_text='A brief description of the category', null=True),
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
