# Generated by Django 5.1.3 on 2024-12-30 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_skillcategory_description_alter_skillcategory_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name for the project', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the category', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'project_category',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category of the project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectcategory'),
        ),
    ]
