# Generated by Django 5.1.3 on 2024-12-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_category_alter_project_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='skills',
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(to='projects.skill'),
        ),
    ]
