# Generated by Django 5.1.3 on 2025-01-03 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
