# Generated by Django 5.1.3 on 2025-04-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='approach_methodology',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='available_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='questions_for_client',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='relevant_experience',
            field=models.TextField(blank=True),
        ),
    ]
