# Generated by Django 5.1.3 on 2025-04-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_alter_proposal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='is_shortlisted',
            field=models.BooleanField(default=False),
        ),
    ]
