# Generated by Django 5.1.3 on 2025-04-09 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatmessage_table_alter_chatroom_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chatmessage',
            table='chat_messages',
        ),
        migrations.AlterModelTable(
            name='chatroom',
            table='chat_rooms',
        ),
    ]
