# Generated by Django 5.1.3 on 2025-04-10 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatmessage_read_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='read_at',
            new_name='seen_at',
        ),
    ]
