# Generated by Django 5.1.3 on 2025-04-10 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_rename_read_at_chatmessage_seen_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='seen_at',
        ),
    ]
