# Generated by Django 5.1.3 on 2025-02-18 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='url',
        ),
    ]
