# Generated by Django 5.1.3 on 2024-12-27 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='company',
        ),
    ]
