# Generated by Django 5.1.3 on 2024-12-27 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_middle_name_alter_user_first_name_and_more'),
        ('clientprofile', '0002_alter_company_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='client_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='accounts.client'),
            preserve_default=False,
        ),
    ]
