# Generated by Django 5.1.3 on 2024-12-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientprofile', '0003_company_client_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='client_ID',
            new_name='client',
        ),
    ]
