# Generated by Django 5.1.3 on 2025-04-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='redirect_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
